version: '3.3'
services:
  postgres:
    image: "postgres:12.3"
    environment:
      POSTGRES_USER: testmicro
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mybookscollection
    ports:
      - 5432:5432